### ISSUE TITLE
Overflowing tabs scroller?

### ISSUE THREAD

**Issue by asifmohtesham** [k-ivan/tabs-slider#7]
### Compliment
Smooth, fast, and easy to implement. Great work, loved it!

### Requirement
I have about 10 tabs that require to be scrolled in order for the hidden (out of the viewport) tabs to be visible. Anyway we can achieve this without ```overflow: auto``` since it is ugly on most browsers? It'd be great if we could slide past the current tabs and make visible the ones out of the viewport.

**Comment by k-ivan** [comment]
Hello @asifmohtesham  and thank you!

Yes, it can be thought out more elegantly. I'll try to think about it when I have time.

**Comment by k-ivan** [comment]
Hi @asifmohtesham

In the end I decided not to hide the scrolling, but added a little functionality to the tabs, if the active tab does not fit into the visibility area, then an automatic scroll to the active tab occurs so that it fully appears in the visibility area.

Regarding the scrollbar, I would like to suggest that you remove it using styles, for example:

```css
.tabs__bar {
  /* IE */
  -ms-overflow-style: none;
  /* Firefox */
   scrollbar-width: none;
}
/* Chrome, Safari */
.tabs__bar::-webkit-scrollbar {
  display: none;
}
```

I think this is the most convenient way
